#default
spring:
  profiles:
    active: client1

---

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: eureka-client
  profiles: client1

---

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: eureka-client
  profiles: client2


