server:
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://backup:8762/eureka/
  instance:
    hostname: master
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 2000

spring:
  application:
    name: eureka-server
  profiles: master

---

server:
  port: 8762
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://master:8761/eureka/
  instance:
    hostname: backup
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 2000
spring:
  application:
    name: eureka-server
  profiles: backup