server:
  port: 8762
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://master:8761/eureka/
  instance:
    hostname: backup
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 2000
